"""
Project Euler Problem 12
========================

The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
28. The first ten terms would be:

                 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

   1: 1
   3: 1,3
   6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five
divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""
import math


def triangular_number():
    n = 1
    while True:
        count_factor = 0
        triangle_number = n * (n + 1) / 2
        n += 1
        square_root = math.sqrt(triangle_number)
        for i in range(1, int(square_root + 1)):
            if triangle_number % i == 0:
                count_factor = count_factor + 1
        count_factor = 2 * count_factor - 1 if square_root ** 2 == triangle_number else 2 * count_factor
        if count_factor > 500:
            return int(triangle_number)


if __name__ == '__main__':
    print(triangular_number())
